[package]
name = "task_scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46", features = ["full"] }
sha2 = "0.10"
blake3 = "1.5"
digest = "0.10"
thiserror = "2.0.17"
